#默认使用配置
spring:
  profiles:
    active: dev
  server:
    port: 8080
    context-path: /fish


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.fish.salted.entity
  mapperLocations: classpath:mapper/*.xml

---

#开发配置
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/exam?serverTimezone=GMT%2B8
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    #type: com.alibaba.druid.pool.DruidDataSource